### ISSUE TITLE
Support --output-format=terse

### ISSUE THREAD

**Issue by weaversa** [model-checking/kani-github-action#10]
Requested feature: Support Kani's `--output-format=terse` option.
Use case: Ease of viewing the CI log.

Test case: Here are two views, one w/ terse and one w/out -- https://github.com/weaversa/aes-rust/actions/runs/3388002019/jobs/5629452264

**Comment by danielsn** [comment]
Thanks for the suggestion.  Currently, you can specify additonal arguments using the optional `args` flag to the CI action.  e.g. 
```yaml
      - name: Kani run
        uses: model-checking/kani-github-action@v0.13
        with:
          args: --output-format=terse
```
